language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
    - ROS_DISTRO=noetic
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script 
